### ISSUE TITLE
dev的OCR有bug?

### ISSUE THREAD

**Issue by 605527108** [NKUCodingCat/NKU-SSS#7]
刷了几张验证码，然后就卡住了

**Comment by NKUCodingCat** [comment]
啊咧QAQ……氖做了什么？

**Comment by 605527108** [comment]
没做什么，计划做一个API，自动识别验证码，返回验证码内容和cookie的json数据

**Comment by NKUCodingCat** [comment]
诶……你检查一下是不是因为网络问题或者什么……一般来说不会识别不了吧……【反正不是我写的╮(￣▽￣")╭ 】

**Comment by Neon4o4** [comment]
我下课回去改一下  顺利的话预计今天晚上或明天解决_(: 3」∠)_

**Comment by NKUCodingCat** [comment]
学长加油

**Comment by Neon4o4** [comment]
改了 试试最新版

**Comment by Neon4o4** [comment]
...好古老的 issue，，

**Comment by NKUCodingCat** [comment]
其实我早就写了个新版的OCR然而一直忘了关这个wwww
